apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: image-clone-system
namePrefix: image-clone-

commonLabels:
  app: image-clone-controller

resources:
- namespace.yaml
- manager.yaml
- ../rbac

images:
- name: controller
  newName: ghcr.io/timebertt/image-clone-controller
  newTag: latest
