apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
- role: control-plane
  image: kindest/node:v1.24.2
  extraPortMappings:
  # registry
  - hostPort: 5001 # makes the registry accessible from the host as localhost:5001
    containerPort: 30501 # nodePort of Service registry/registry
containerdConfigPatches:
- |-
  [plugins."io.containerd.grpc.v1.cri".registry.mirrors."localhost:5001"]
    endpoint = ["http://image-clone-controller-control-plane:30501"]
